spring.config.import=optional:file:env.properties

spring.application.name=ms-registro
server.port=${PORT:${SERVER_PORT:8081}}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Limita a 2 o 3 conexiones por microservicio
spring.datasource.hikari.maximum-pool-size=1
# Tiempo máximo de espera para obtener una conexión
spring.datasource.hikari.connection-timeout=30000
# Tiempo máximo que una conexión puede estar inactiva
spring.datasource.hikari.idle-timeout=600000
