spring.config.import=optional:file:env.properties

spring.application.name=ms-registro
server.port=${PORT:${SERVER_PORT:8081}}

# Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=2

# NUEVO: Seguridad Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}

# NUEVO: Ruta del microservicio de notificaciones
ms.notificaciones.url=${MS_NOTIFICACIONES_URL}