server:
  port: ${PORT}

spring:
  application:
    name: ms-gestion
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Eliminamos la sección de security de aquí para que mande el SecurityConfig.java
logging:
  level:
    org.springframework.security: DEBUG